Now uses an sqlite3 database for its tracking. Regenerates it when db file is older than 24h age.
Added a new (DEFAULT ON) "preferNativeRes=yes" entry in the conf file
which will only select images that match your current resolution.

May create an initial "setup" y/n question bootstrap stage later for
those with good preferences.

diff --git a/wallpaperSetter b/wallpaperSetter
--- a/wallpaperSetter
+++ b/wallpaperSetter
@@ -1,86 +1,179 @@
 #!/bin/bash
 VERSION=0.6
 
-#Display for 'feh' to throw wallpapers at.
-export DISPLAY=':0'
+  # Fallback $DISPLAY variable to :0.
+if [ -z $DISPLAY ]; then export DISPLAY=':0'; fi
+
 _configFile="$(dirname $(realpath $0))/$(basename $0).conf"
+_dbFile="$(dirname $(realpath $0))/$(basename $0).db"
+_dbTable="$(basename $0)"
 
-
-function log {
+function log { 
+    # 'logger' call with 'echo' session interactive
   if [ ! -z $- ] ; then echo ${1} ; fi
   logger "$0 ${1}"
 }
 
+function logDebug() {
+    # Same as above but only if DEBUG=1
+  if [ "$DEBUG" == "1" ]
+  then
+    log "$@"
+  fi
+}
+
 function dependencyChecker {
-  #Search for tools and die if missing. Checks all arugments.
+    # Check for all programs heard as args
   _dependencies="$@"
   for program in $_dependencies
   do
     if ! which $program > /dev/null
       then
-        echo "Dependency software :$tool: not found in your PATH. Please install/provide it or edit in a substitute" && exit 1
+        echo "Dependency program :$program: not found in your PATH. Please install/provide it or edit in a substitute" && exit 1
     fi
   done
 }
 
 function readConfig {
-  #Sets vars from config, quits if they're not found.
-  _wantedVars="$@" #What we search for
-
-  for configOption in $_wantedVars
-   do
-      #If not found, warn and exit with an error
-      if var=$(grep -E "^$configOption=.*$" $_configFile)
-      then
-        eval $var #Set it
-      else
-        echo "Cannot find variable :$configOption: in $_configFile, please set it before running"
-	exit 1
-      fi
-  done
-
-}
-
   #Generate the config if missing
 if [ ! -f $_configFile ];
 then
   cat > $_configFile << EOF
 #Generated by version $VERSION
 
-#Dirs and Options
+###Dirs and Options
+
 WPDirectory="\$HOME/Wallpapers/"
 WPRecursion="no"
 
-  #Fill or Scale images to your monitors (Preference)
+###Preferences
+
+  # Fill or Scale images to display?
 bgmode=fill
 #bgmode=scale
+
+  # Try to fetch current-resolution bgs only?
+preferNativeRes=yes
+
+  # Regenerate the DB if older than this many seconds
+dbStaleTime="86400" #A day
 EOF
 fi
 
+    # Sets vars from config, quits if they're not found.
+  _wantedVars="$@" #What we search for
+
+  for configOption in $_wantedVars
+   do
+      #If not found, warn and die
+      if var=$(grep -E "^$configOption=.*$" $_configFile)
+      then
+        eval $var #Set it
+      else
+        echo "Cannot find variable :$configOption: in $_configFile, please set it or consider deleting an older configuration so I can regenerate a new one."
+	exit 1
+      fi
+  done
+
+}
+
+function genDb {
+  log "Database must be (re)generated.. stand by..."
+
+    # Disable recursion if 'no' specified.
+  if [ "$WDRecursion" == "no" ] ; then recurseFlag="-maxdepth 1"; fi
+
+    # Find, identify dimensions and format findings as INSERT queries.
+  allWallpapers="$(find "$WPDirectory" $recurseFlag -type f -exec echo -n \'{}\', \; -exec identify -format "'%wx%h'\n" {} \;|while read line; do echo "insert into $_dbTable values($line);"; done)"
+
+    # Remove any old (Probably a bad idea)
+  rm -f $_dbFile
+
+    # Make the new file, table and populate it with the filename and dimensions.
+  sqlite3 $_dbFile <<EOF
+CREATE TABLE $_dbTable ( path varchar(255), res varchar(255) );
+$allWallpapers
+EOF
+}
+
+function dbPrep {
+  if [ ! -f $_dbFile ]; then genDb; fi #If missing, generate.
+
+  if [ "$(date -r $_dbFile +%s)" -lt "$(((`date +%s` - $dbStaleTime)))" ]
+  then
+    log "Database is over $_dbStaleTime seconds old, regenerating to catch new changes"
+    genDb #Regen the database
+  fi
+}
+
+function help {
+  /bin/echo "Set random backgrounds automatically from $HOME/Wallpapers (Or another configured directory!)"
+  /bin/echo "Usage examples:"
+  /bin/echo "$0 (optional extras: -help -debug -regendb/-regen)"
+  exit 1
+}
+
+### Read any args
+
+while [ $# -gt 0 ]
+do
+  case "$1" in
+    -regendb|-regen)
+	REGEN="1"
+        shift
+    ;;
+     -verbose|-debug)
+        VERBOSE="1" && DEBUG="1"
+    ;;
+     help|-help)
+        help
+    ;;
+     *) /bin/echo "Unknown argument $1"
+        help
+    ;;
+    esac
+    shift
+done
+
+
 ### GO
 
-  #Check deps
-dependencyChecker "date dirname feh find grep logger xrandr"
+  #Check deps.
+dependencyChecker "date dirname feh find grep identify logger xrandr"
 
-  # Set vars from conf
-readConfig "WPDirectory WPRecursion bgmode"
+  # Read config for these args.
+readConfig "WPDirectory WPRecursion bgmode preferNativeRes dbStaleTime"
 
-  # Determine active displays
+  # Determine active display count.
 imageFetchCount="$(xrandr --query|grep -w 'connected'|wc -l)"
 
-  # Set recursion level
-if [ "$WDRecursion" == "no" ] ; then recurseFlag="-maxdepth 1"; fi
-  # Get image list
-wallpaperList="$(find "$WPDirectory" $recurseFlag)" 
 
-  # Shuffle list and pick x images based on active displays
-RandomlyChosen=$(echo "$wallpaperList"| shuf -n$imageFetchCount)
+# Check DB status and regen if required.
+if [ ! -z $REGEN ]
+then
+  genDb #Force if $REGEN defined
+else
+  dbPrep #Do our 24h check anyway
+fi
 
-  # Build arguments for 'feh'
-fehArguments=$(while read chosenImage ; do echo -n "--bg-$bgmode" "\"$chosenImage\" " ;   done <<<"$RandomlyChosen") #It wouldn't look like this if whitespace characters didn't ruin everything.
+  # Select x random images from the db based on active displays.
+if [ "$preferNativeRes" == "yes" ]
+then
+  primaryRes="$(xrandr | grep \* | awk '{print $1}'|head -n1)"
+  resQuery="where res = '$primaryRes'"
+fi
+
+randomImages="$(sqlite3 $_dbFile "select path from wallpaperSetter $resQuery order by random() limit $imageFetchCount;")"
+
+
+logDebug "$randomImages"
+
+  # Build arguments for 'feh'. Supports whitespace filenames.
+fehArguments=$(while read chosenImage ; do echo -n "--bg-$bgmode" "\"$chosenImage\" " ;   done <<<"$randomImages")
 
   #Log so people can check what was picked later.
 log "$(basename $0) - $(date) - feh $fehArguments"
+
 
   #Eval our command.
 eval feh $fehArguments
