Fixed typo in recursion var.
Added general function to fetch images. If it can't find {x} native-res
images, it will just requery for "any" resolution. If it somehow turns
up with "0" results it gives up.

diff --git a/wallpaperSetter b/wallpaperSetter
--- a/wallpaperSetter
+++ b/wallpaperSetter
@@ -41,7 +41,8 @@ function readConfig {
 if [ ! -f $_configFile ];
 then
   cat > $_configFile << EOF
-#Generated by version $VERSION
+# Generated by version $VERSION
+# This conf can be deleted at any time for a regenerated default copy.
 
 ###Dirs and Options
 
@@ -83,12 +84,12 @@ function genDb {
   log "Database must be (re)generated.. stand by..."
 
     # Disable recursion if 'no' specified.
-  if [ "$WDRecursion" == "no" ] ; then recurseFlag="-maxdepth 1"; fi
+  if [ "$WPRecursion" == "no" ] ; then recurseFlag="-maxdepth 1"; fi
 
     # Find, identify dimensions and format findings as INSERT queries.
   allWallpapers="$(find "$WPDirectory" $recurseFlag -type f -exec echo -n \'{}\', \; -exec identify -format "'%wx%h'\n" {} \;|while read line; do echo "insert into $_dbTable values($line);"; done)"
 
-    # Remove any old (Probably a bad idea)
+    # Remove any old (Probably an unsafe idea)
   rm -f $_dbFile
 
     # Make the new file, table and populate it with the filename and dimensions.
@@ -106,6 +107,24 @@ function dbPrep {
     log "Database is over $_dbStaleTime seconds old, regenerating to catch new changes"
     genDb #Regen the database
   fi
+}
+
+function fetchRandomImages {
+  randomImages="$(sqlite3 $_dbFile "select path from wallpaperSetter $resQuery order by random() limit $imageFetchCount;")"
+  
+  if [ "$(wc -l <<<"${randomImages}")" -lt "$imageFetchCount" ]
+  then
+  log "Not enough $resQuery images to satisfy the monitors. Accepting any resolution"
+  randomImages="$(sqlite3 $_dbFile "select path from wallpaperSetter $resQuery order by random() limit $imageFetchCount;")"
+    if [ "$(wc -l <<<"${randomImages}")" -eq "0" ]; then log "Couldn't find any images? Exiting in panic" ; exit 1; fi
+  fi
+
+  while read randomImage #Check if they exist
+  do
+    if [ ! -f "$randomImage" ]; then log "Image in db not found, regenerating..." ;genDb; fi
+    randomImages="$(sqlite3 $_dbFile "select path from wallpaperSetter $resQuery order by random() limit $imageFetchCount;")" #Should make this a function
+  done <<<$"$randomImages"
+ 
 }
 
 function help {
@@ -165,8 +184,9 @@ then
   resQuery="where res = '$primaryRes'"
 fi
 
-randomImages="$(sqlite3 $_dbFile "select path from wallpaperSetter $resQuery order by random() limit $imageFetchCount;")"
+fetchRandomImages
 
+ 
 
 logDebug "$randomImages"
 
