Loops through all deps and only prints the error after it knows the status of all deps. Instead of exiting just after one. This time without test args in the program!

diff --git a/wallpaperSetter b/wallpaperSetter
--- a/wallpaperSetter
+++ b/wallpaperSetter
@@ -27,11 +27,13 @@ function dependencyChecker {
   _dependencies="$@"
   for program in $_dependencies
   do
-    if ! which $program > /dev/null
+    if ! which $program > /dev/null 2>&1
       then
-        echo "Dependency program :$program: not found in your PATH. Please install/provide it or edit in a substitute" && exit 1
+        missing="$missing$program "
     fi
   done
+
+  if [ ! -z "$missing" ]; then echo "Dependency programs :$missing: not found in your PATH. Please provide the path, install their packages or provide a substitute." && exit 1; fi
 }
 
 function readConfig {
