Long needed changes added.
Turned some variables relying on newline delimiters into arrays.

Fixed failure mode if trying to find a spanning wallpaper when there are
multiple screens of different resolutions, fails and tries to span a
single wallpaper across all monitors poorly.

Changed wallpaper scanning process to take checksums of images to
compare with the existing database so they may be skipped if already
seen and with the same checksum as the previous scan. (This does not yet
remove old images, so is prone to error if images are removed and
rescan, but not remove them from the database until corrected).

Some sanity checking of the database state will also need to be done and
only then should a full rebuild (drop table) be done to recreate upon
seeing a severe error in expected db formatting or output.

diff --git a/wallpaperSetter b/wallpaperSetter
--- a/wallpaperSetter
+++ b/wallpaperSetter
@@ -37,12 +37,12 @@ fi
 
 
 function log {
-  if [ -t 1 ]; then logcommand=echo; else logcommand=logger && prefix="$_name - "; fi # use echo if stdout is a terminal
+  if [ -t 1 ]; then logcommand="echo -e"; else logcommand=logger && prefix="$_name - "; fi # use echo if stdout is a terminal
 
   if [ "$DEBUG" == "1" ] && [[ "$1" =~ "DEBUG" ]]
   then
-    echo "${prefix}${@}"
-    logger "${prefix}${@}"
+    echo -e "${prefix}${@}"
+    logger "$(echo -e "${prefix}${@}")"
   elif [[ ! "$1" =~ "DEBUG" ]]
   then
     $logcommand "${prefix}${@}"
@@ -97,7 +97,7 @@ function showDb {
   if [ -f "$_dbFile" ]
   then
     log "Showing current DB contents then exiting"
-    sqlite3 $_dbFile 'select res,path from wallpaperSetter;' | sed 's/|/\t/g'
+    sqlite3 $_dbFile "select * from $_dbTable;" | sed 's/|/\t/g'
   else
     log "DB file not found ($_dbFile), one must be generated first."
   fi
@@ -123,15 +123,44 @@ function genDb {
   fi
 
     # Find, identify dimensions and format findings as INSERT queries.
-  allWallpapers="$(find "${WPDirectory}" ${recursionFlags} -type f -exec echo -n \"{}\", \; -exec identify -format '"%wx%h"\n' "{}" 2>/dev/null \;|while read line; do echo "insert into $_dbTable values($line);"; done)"
-  set +o noglob
-  log "DEBUG: $allWallpapers"
+  allWallpapers="$(find "${WPDirectory}" ${recursionFlags} -type f)"
+  allCount=$(wc -l <<< $allWallpapers)
+
+  echo -e "Indexing now. $allCount images found."
+
+
+  while read wallpaperFile
+  do
+      unset checksum ; checksum=$(sha1sum "$wallpaperFile" | awk '{ print $1 }')
+
+      # Check if we've already scanned this one before building an insert query for it.
+    pathCheckresult="$(sqlite3 $_dbFile <<< "select path from $_dbTable where path = '$wallpaperFile';" | wc -l)"
+    if [ $pathCheckresult -gt 0 ]
+    then
+      checksumCheckresult=$(sqlite3 $_dbFile <<< "select checksum from $_dbTable where path = '$wallpaperFile' and checksum = '$checksum';" | wc -l)
+      if [ $checksumCheckresult -gt 0 ]
+      then
+        log "DEBUG: Checksum still matches, skipping: $wallpaperFile."
+        continue
+      fi
+    fi
+
+    if [ ! -z "$DEBUG" ] ; then (((index++))) ; echo $index ; fi
+
+    wallpaperDims="$(identify -format '%wx%h' "$wallpaperFile")"
+    colorProfile="$(convert "$wallpaperFile" -resize 1x1\! -resize 1x1 txt:-|grep -Eo '\#([0-9]|[A-F]){6}')"
+    sql+=("insert or replace into $_dbTable values(\"$wallpaperFile\",\"$wallpaperDims\",\"$colorProfile\", \"$checksum\");")
+    done <<< $allWallpapers
+
     # Make the new file, table and populate it with the filename and dimensions.
   sqlite3 $_dbFile <<EOF
-    DROP TABLE IF EXISTS $_dbTable;
-    CREATE TABLE $_dbTable ( path varchar(255), res varchar(255) );
-$allWallpapers
+  CREATE TABLE if not exists $_dbTable ( path varchar(255), res varchar(255), profile varchar(6), checksum varchar(40), UNIQUE(path) );
 EOF
+
+  for line in "${sql[@]}"
+  do
+    echo "$line" | sqlite3 $_dbFile
+  done
 }
 
 function dbPrep {
@@ -157,22 +186,23 @@ function queryDb {
 
 function fetchRandomImages {
 
-  result="$(queryDb "select path from $_dbTable $resQuery order by random() limit $imageFetchCount;")"
+  readarray -t queryResults <<< $(queryDb "select path from $_dbTable where res = \'$searchRes\' order by random() limit $imageFetchCount;")
 
-  if [ "$(grep -v '^$' <<< "$result" |wc -l)" -lt "$imageFetchCount" ]
+  if [ ${#queryResults[@]} -lt $imageFetchCount ] || [ -z "${queryResults[0]}" ] # Check total results aren't too short and first entry isn't blank.
   then
-    log "DEBUG: Not enough $resQuery results for these monitors. Accepting any resolution"
-    result="$(queryDb "select path from $_dbTable order by random() limit $imageFetchCount;")"
-    if [ "$(grep -v '^$' <<< $result |wc -l)" -lt "$imageFetchCount" ]; then log "DEBUG: Couldn't find any images? Regenerating and exiting in panic" ; genDb ; exit 1; fi
+    log "DEBUG: Not enough $searchRes results for these monitors. Falling back and accepting any resolution wallpaper."
+    searchRes=$primaryRes
+    readarray -t queryResults <<< $(queryDb "select path from $_dbTable order by random() limit $totalMonitors;")
+    if [ ${#queryResults[@]} -lt $imageFetchCount ]; then log "DEBUG: Couldn't find any enough images? Regenerating and exiting in panic" ; genDb ; exit 1; fi
   fi
 
-  echo "$result" | while read image # Check if they exist
+  for imageIndex in ${!queryResults[@]} # Check if they exist
   do
-    log "DEBUG: testing whether :$image: exists."
-    if [ ! -f "$image" ]; then log "Db returned non-existent image, regenerating..." ;genDb; fi
+    log "DEBUG: testing whether :${queryResults[imageIndex]}: exists."
+    if [ ! -f "${queryResults[imageIndex]}" ]; then log "Db returned non-existent image file, regenerating database now and exiting." ;genDb; exit 1; fi
   done
-
-  echo "${result}"
+  
+  #echo ${queryResults[@]}
 }
 
 function help {
@@ -224,7 +254,8 @@ done
 readConfig "WPDirectory WPRecursion bgmode tryNativeRes trySpanWallpapers dbStaleTime spanWallpaperPercentChance"
 
   # Determine active display count.
-imageFetchCount="$(xrandr --listactivemonitors | grep -oP '(?<=Monitors:\ )[0-9]+')"
+totalMonitors="$(xrandr --listactivemonitors | grep -oP '(?<=Monitors:\ )[0-9]+')"
+imageFetchCount="$totalMonitors"
 combinedRes="$(xrandr |grep -Po '(?<=current\ )[0-9]+ x [0-9]+' | tr -d ' ')"
 primaryRes="$(xrandr | grep \* | awk '{print $1}'|head -n1)"
 
@@ -241,22 +272,32 @@ if [ "$tryNativeRes" == 'yes' ] && [ "$trySpanWallpapers" == 'yes' ]
 then
     #Diceroll for which we go with
   diceResult="$(($RANDOM % 100))"
-  if [ $diceResult -le $spanWallpaperPercentChance ]; then searchRes=$combinedRes && imageFetchCount=1 ; else searchRes=$primaryRes ; fi
-elif [ "$tryNativeRes" == 'yes' ] ;      then searchRes=$primaryRes ;
-elif [ "$trySpanWallpapers" == 'yes' ] ; then searchRes=$combinedRes 
+  if [ $diceResult -le $spanWallpaperPercentChance ]
+    then searchRes=$combinedRes && imageFetchCount=1
+    else searchRes=$primaryRes
+  fi
+
+elif [ "$tryNativeRes" == 'yes' ]
+then
+  searchRes=$primaryRes
+
+elif [ "$trySpanWallpapers" == 'yes' ]
+then
+  searchRes=$combinedRes 
+
 fi
 
-resQuery="where res = '$searchRes'"
-randomImages="$(fetchRandomImages)"
+fetchRandomImages
 
-log "DEBUG: randomImages = $randomImages"
+log "DEBUG: queryResults = ${queryResults[@]}"
 
   # Build arguments for 'feh'. Supports whitespace filenames.
 if [ "$searchRes" == "$combinedRes" ]
 then
-  fehArguments="--bg-tile \"$randomImages\"" # --bg-tile works for multi-monitor wallpapers.
+  fehArguments="--bg-tile \"$queryResults\"" # --bg-tile works for multi-monitor wallpapers.
 else
-  fehArguments=$(while read chosenImage ; do echo -n "--bg-$bgmode" "\"$chosenImage\" " ;   done <<<"$randomImages")
+  #fehArguments=$(while read chosenImage ; do echo -n "--bg-$bgmode" "\"$chosenImage\" " ;   done <<<"${queryResults[@]}")
+  fehArguments=$(for imageIndex in ${!queryResults[@]}; do echo -n "--bg-$bgmode" "\"${queryResults[$imageIndex]}\" "; done)
 fi
 
   # Log what's been picked for later checking.
